1 - Array module
cairo-book/cairo-core-lib pull request #1
Opened 2024-10-29 14:30 UTC by TAdev0

2024-10-29 14:32 UTC, TAdev0 commented on corelib/src/array.cairo
> -/// Returns a box of struct of members of the same type from a span.
removed this comments as we never directly use extern fn, these are internal functions for following `try_into` function

or should i leave these comments with `//` instead of `///` so that it doesnt appear in the documentation?

2024-10-29 14:33 UTC, TAdev0 commented on corelib/src/array.cairo
> -/// level, where it is deduced by the `T` type.
also removed as internally used in `span` function

2024-10-30 05:10 UTC, enitrat requested changes
Made some comments about things to change globally, not being too vague but also not too verbose.

Haven't reviewed everything yet, I will let you review this first batch and apply changes throughout the entire document.

Some help:
- https://doc.rust-lang.org/src/alloc/vec/mod.rs.html
- https://doc.rust-lang.org/std/vec/struct.Vec.html
- https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html
- https://github.com/rust-lang/rfcs/pull/1687
- https://rust-lang.github.io/api-guidelines/documentation.html

2024-10-30 05:10 UTC, enitrat commented on corelib/src/array.cairo
> +/// `Into` trait implementation to convert a span into an array.
```suggestion
```

2024-10-30 05:10 UTC, enitrat commented on corelib/src/array.cairo
> +    /// ```
on when to document or not an implementation of a trait:

- base case is: don't document a trivial impl of a trait (e.g. imagine a conceptual type `U8Wrapper(u8)`, then `Into<u8, U8Wrapper>` is a trivial implementation of that type and doesn't need doc, and the default documentation of the trait should take precedence.


- However, if we want to highlight something specific, then we can add documentation.

In this specific case, what's important is to understand that turning a Span<T> into an Array<T> is a __*O*(n)__ operation that requires  re-allocating a new memory segment, which is missing from the current doc.



```suggestion
    /// Turn a [`Span<T>`] into a [`Array<T>`]
    ///
    /// This needs to allocate a new memory segment for the returned array, and *O*(*n*) operations to populate the array with the content of the span.
    /// # Examples
    ///
    /// ```
    /// let input: Span<u8> = array![1, 2, 3].span();
    /// let output: Array<u8> = span.into();
    /// assert_eq!(input, output.span());
    /// ```
```

2024-10-30 05:10 UTC, enitrat commented on corelib/src/array.cairo
> +    /// ```
For this one, I would consider it OK to not have any associated doc, as it's a trivial implementation with no side-effects. The generic doc of `Into<T, U>` would take over.

2024-10-30 10:15 UTC, TAdev0 commented on corelib/src/array.cairo
> +/// `Array<T>` derives `Drop` trait.
yes, opened an issue to list missing features for scarb doc

2024-10-30 10:18 UTC, TAdev0 commented on corelib/src/array.cairo
oh ok, i understood we should skip module documentation as scarb doc doesnt support it. Ok lets use it and improve scarb doc later to support it

2024-10-30 10:23 UTC, TAdev0 commented on corelib/src/array.cairo
this top level documentation is meant to be incomplete right? like a general presentation of main features

2024-10-30 10:41 UTC, TAdev0 commented on corelib/src/array.cairo
> +    /// let mut arr: Array<felt252> = array![];
done

2024-10-30 10:45 UTC, TAdev0 commented on corelib/src/array.cairo
> +    /// Returns `Option::Some(value)` if the array is not empty, `Option::None` otherwise.
i'll stick to use explicit option i think, they do it this way in the rust doc mainly

2024-10-30 10:56 UTC, TAdev0 commented on corelib/src/array.cairo
> +    /// assert!(arr.pop_front_consume() == Option::None);
just used `is_none` 
for assertions, i'm using `assert!` not `asssert_eq!` which requires a dev dependency

2024-10-30 11:08 UTC, TAdev0 commented on corelib/src/array.cairo
>      /// ```
done

2024-10-30 11:12 UTC, TAdev0 commented on corelib/src/array.cairo
> +/// `Clone` implementation for `Array<T>`.
so removing the impl level doc but keeping the function level doc? ok

2024-10-30 12:06 UTC, enitrat commented on corelib/src/array.cairo
>  Ok lets use it and improve scarb doc later to support it

Its coming with 2.9 i think

2024-10-30 12:07 UTC, enitrat commented on corelib/src/array.cairo
yes, cf https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html#getting-started

2024-10-30 12:08 UTC, enitrat commented on corelib/src/array.cairo
> this top level documentation is meant to be incomplete right? like a general presentation of main features

yes basically an intro on how to use this module. let's say it contains the most common use cases

2024-10-30 13:29 UTC, TAdev0 commented on corelib/src/array.cairo
got it! thanks

2024-10-31 01:30 UTC, enitrat commented on corelib/src/array.cairo
> +    /// panics with an 'Index out of bounds' error otherwise.
Up

2024-10-31 03:50 UTC, enitrat requested changes

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// `IndexView` needs to be explicitly imported with `use core::ops::IndexView;`
to use? I don't think so (only to implement); or if you really need to import it explicitly, the example needs to be changed

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// `IndexView` needs to be explicitly imported with `use core::ops::IndexView;`
ok I get it; you need to import the trait to use `arr.index` but in reality you want to use the subscript operator `[ ]`

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// assert!(element == @1)
```suggestion
    /// let arr: Array<u8> = array![1, 2, 3];
    /// let element = arr[0];
    /// assert!(element == @1)
```

This is a more realistic way of how to use the IndexView trait with arrays.

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `Copy` trait implementation for `Span<T>`.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `Drop` trait implementation for `Span<T>`.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// ```
please address this one and other similar cases of trivial Into implementations

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `Serde` trait implementation to serialize and deserialize a `Span<T>`.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `Serde` trait implementation to serialize and deserialize a `Span<felt252>`.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// Returns a snapshot of the element at the given index.
same feedback as for arrays

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `ToSpanTrait` implementation for `Array<T>`.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> -/// level, where it is deduced by the `T` type.
see other comment, I think it's fine to keep with (`///`)

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `ToSpanTrait` implementation for a box containing a snapshot of a fixed-size array.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `ToSpanTrait` implementation for a snapshot of a fixed-size array.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// let span: Span<u32> = (@arr).span();
```suggestion
    /// let span = arr.span();
```

- avoid useless explicit types
- avoid explicit snapshot conversions unless strictly necessary

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// let span: Span<u32> = (@arr).span();
```suggestion
    /// let span = arr.span();
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> -/// Returns a box of struct of members of the same type from a span.
> or should i leave these comments with // instead of /// so that it doesnt appear in the documentation?

I would be of opinion to keep them even if they're not generated by documentation tools. They might be useful to contributors to the source code.

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// ```
same as for the `Default` trait impl, this is more a documentation of the `Clone` trait rather than this specific impl, so not strictly required.

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// ```
```suggestion
```

imo this could just inherit the base `PartialEq::eq` doc. Eventually we could keep the first line.

If we had kept the example, we would use `==` and not `PartialEq::eq`.

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// ```
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `Drop` trait implementation for `SpanIter<T>` struct.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `Copy` trait implementation for `SpanIter<T>` struct.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `Iterator` trait implementation for `SpanIter<T>` struct.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// Type of the elements contained in the span.
```suggestion
```

would inherit the base trait documentation which would be something like
"The type of the elements being iterated over."

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// Returns an option of a snapshot of a span element if it exist, and `Option::None` otherwise.
would inherit the base trait documentation, something like 
```
Advances the iterator and returns the next value.

Returns `Option::None` when iteration is finished. 
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `IntoIterator` trait implementation for `Span<T>`.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// Returns a `SpanIter<T>` given a `Span<T>`.
```suggestion
```
would inherit the base trait doc, which would be something like:

"The kind of iterator we are turning this into"

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `Clone` trait implementation for `ArrayIter<T>` struct.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// Returns a clone of `self`.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `Iterator` trait implementation for `ArrayIter<T>` struct.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// Type of the elements contained in the array.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// Returns an option of an element of the array if it exists, and `Option::None` otherwise.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// `IntoIterator` trait implementation for `Array<T>`.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +    /// Returns an `ArrayIter<T>` given an `Array<T>`.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// containing elements of type `T`.
```suggestion
```

2024-10-31 03:50 UTC, enitrat commented on corelib/src/array.cairo
> +/// containing elements of type `T`.
note: in that case I would have suggested to add doc to the base trait instead, but considering that it's an internal trait not meant to be used by the public, we could do nothing.

2024-11-04 17:49 UTC, TAdev0 commented on corelib/src/array.cairo
> +    /// ```
removed

2024-11-04 17:51 UTC, TAdev0 commented on corelib/src/array.cairo
> +    /// `IndexView` needs to be explicitly imported with `use core::ops::IndexView;`
added examples with both

2024-11-05 14:21 UTC, enitrat reviewed
just a few items to resolve / discuss about, and lgtm

process: 

approval here -> submit PR on cairo repo -> merge there

How does that sound ?

2024-11-05 14:21 UTC, enitrat commented on corelib/src/array.cairo
> +    /// ```
```suggestion
    /// Returns a snapshot of the element at the given index.
    ///
    /// # Examples
    ///
    /// ```
    /// let arr: @Array<u8> = @array![1, 2, 3];
    /// let element: @u8 = arr.index(0);
    /// assert!(element == @1);
    ///
    /// let element: @u8 = arr[0];
    /// assert!(element == @1);
    /// ```
```

My take here: `index` is, in reality, not something you would want to use directly. The purpose of implementing the indexview trait is to have access to the `[]` operator

2024-11-05 15:39 UTC, TAdev0 commented on corelib/src/array.cairo
> +    /// ```
Yeah that's why I added an additional example so that we can see both usage in the doc

2024-11-05 15:40 UTC, TAdev0 commented
Was thinking of letting all PRs open , and once I'm done and we agree on few residual things regarding formatting / content, push all the PRs in a row on the Cairo Starkware repo. Is it ok?

2024-11-05 17:30 UTC, enitrat commented on corelib/src/array.cairo
> +    /// Returns a snapshot of the element at the given index.
up (maybe its hidden for you)

2024-11-05 17:31 UTC, enitrat commented
> Was thinking of letting all PRs open , and once I'm done and we agree on few residual things regarding formatting / content, push all the PRs in a row on the Cairo Starkware repo. Is it ok?

Sounds good! 

Also, now that we have settled on a more precise format: can you go over the older PRs again and adapt them, taking into account the feedback made in this PR ?

2024-11-08 13:12 UTC, enitrat approved these changes

2024-11-11 17:06 UTC, merged