10 - Zeroable module
cairo-book/cairo-core-lib pull request #11
Opened 2024-11-04 15:41 UTC by TAdev0

2024-11-14 08:09 UTC, enitrat requested changes

2024-11-14 08:09 UTC, enitrat commented on corelib/src/zeroable.cairo
> +//! ```
```suggestion
//! Types and traits for handling non-zero values and zero checking operations.
//! 
//! This module provides the [`NonZero`] wrapper type which guarantees that a value is never 
//! zero.
//! The [`Zeroable`] trait is meant for internal use only. The public-facing equivalent is the [`Zero`] trait.
//!
//! [`Zero`]: core::num::traits::zero::Zero
```

Your example uses the Zero trait, which isn't really related to this module. The Zeroable trait is an internal-only trait, the public version of it is Zero

2024-11-14 08:09 UTC, enitrat commented on corelib/src/zeroable.cairo
> +// === Zero ===
```suggestion
```

2024-11-14 08:09 UTC, enitrat commented on corelib/src/zeroable.cairo
> -    /// Implements `Zeroable` for any type that implements `Zero`, `Drop`, and `Copy`.
I would add this back

2024-11-14 08:09 UTC, enitrat commented on corelib/src/zeroable.cairo
> -/// This type guarantees that the wrapped value is never zero.
add this back

2024-11-14 08:09 UTC, enitrat commented on corelib/src/zeroable.cairo
> -/// Unwraps a NonZero<T> to retrieve the underlying value of type T.
add this back

2024-11-14 22:50 UTC, TAdev0 commented on corelib/src/zeroable.cairo
> -    /// Implements `Zeroable` for any type that implements `Zero`, `Drop`, and `Copy`.
done with `//` not to generate doc

2024-11-14 22:50 UTC, TAdev0 commented on corelib/src/zeroable.cairo
> -/// This type guarantees that the wrapped value is never zero.
done

2024-11-14 22:54 UTC, TAdev0 commented on corelib/src/zeroable.cairo
> -/// Unwraps a NonZero<T> to retrieve the underlying value of type T.
same, added with `//` as its not supposed to be doc, it s not public

2024-11-15 03:41 UTC, enitrat commented on corelib/src/zeroable.cairo
> -/// Unwraps a NonZero<T> to retrieve the underlying value of type T.
oh yeah right mb

2024-11-18 14:50 UTC, enitrat approved these changes

2024-11-29 04:30 UTC, closed without merging