11 - Traits module
cairo-book/cairo-core-lib pull request #12
Opened 2024-11-04 16:26 UTC by TAdev0

2024-11-14 08:11 UTC, enitrat commented on corelib/src/traits.cairo
> +/// `Drop` trait for dropping values.
Same feedback as copy

2024-11-14 08:22 UTC, enitrat requested changes
I think this modules deserves a second, in-depth approach

2024-11-14 08:22 UTC, enitrat commented on corelib/src/traits.cairo
> +/// `Add` trait for addition of two values of the same type.
Needs more details or example

```suggestion
/// The addition operator `+`.
/// #[derive(Copy, Drop, PartialEq)]
/// struct Point {
///     x: i32,
///     y: i32,
/// }
///
/// impl PointAdd of Add<Point>{
///     fn add(lhs: Point, rhs: Point) -> Point {
///         Point {
///             x: lhs.x + rhs.x,
///             y: lhs.y + rhs.y,
///         }
///     }
/// }
///
/// fn main(){
///     let p1 = Point { x: 1, y: 0 };
///     let p2 = Point { x: 2, y: 3 };
///     let p3 = p1 + p2;
///     assert!(p3 == Point { x: 3, y: 3 });
/// }
///
```

2024-11-14 08:22 UTC, enitrat commented on corelib/src/traits.cairo
> +    // Adds two values of the same type `T` and returns the result of type `T`.
```suggestion
    // Performs the `+` operation.
```

2024-11-14 08:22 UTC, enitrat commented on corelib/src/traits.cairo
> +
Same as Add

2024-11-14 08:22 UTC, enitrat commented on corelib/src/traits.cairo
> +
Same as Mul

2024-11-14 08:22 UTC, enitrat commented on corelib/src/traits.cairo
> +
Same as Add

2024-11-14 08:22 UTC, enitrat commented on corelib/src/traits.cairo
> +
Same as Add.

The documentation should link the operators to their traits explicitly.

2024-11-14 08:22 UTC, enitrat commented on corelib/src/traits.cairo
> +    // Returns whether two values of the same type `T` are equal.
```suggestion
    /// Returns whether `lhs` and `rhs` equal, and is used by `==`.
```

2024-11-14 08:22 UTC, enitrat commented on corelib/src/traits.cairo
> +    // Returns whether two values of the same type `T` are not equal.
```suggestion
    /// Returns whether `lhs` and `rhs` are not equal, and is used by `!=`
```

2024-11-14 08:22 UTC, enitrat commented on corelib/src/traits.cairo
> +/// `PartialEq` trait for checking for equality or inequality between two values of the same type.
```suggestion
/// Trait for comparisons using the equality operator.
///
/// Implementing this trait for types provides the `==` and `!=` operators for
/// those types.
```

Generally,  avoid the `TraitName` trait for doing X and Y formulation

2024-11-18 15:28 UTC, enitrat requested changes
Mostly triival suggestions, however, more info on Default and Felt252DictValue is needed

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Combination of the division operator `/` and the remainder operator `%`.
```suggestion
/// Performs division with remainder, returning both the quotient and remainder.
///
/// This trait provides a way to compute both division and remainder in a single operation,
/// which can be more efficient than computing them separately.
```

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +    /// assert!(DivRem::div_rem(numerator, denominator) == (1, 2));
```suggestion
    /// assert!(DivRem::div_rem(12_u32, 10) == (1, 2));
```

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Trait for computing the AND bitwise operation between two values of the same type.
```suggestion
/// The bitwise AND operator `&`.
```

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Trait for computing the OR bitwise operation between two values of the same type.
```suggestion
/// The bitwise OR operator `|`.
```

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Trait for computing the XOR bitwise operation between two values of the same type.
```suggestion
/// The bitwise XOR operator `^`.
```

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Trait for computing the NOT bitwise operation between two values of the same type.
```suggestion
/// The bitwise NOT operator `~`.
```

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Trait for safe conversion between types.
Would benefit from more actionable descriptions: when should you implement `Into`? When should you not implement `Into`,  but prefer `TryInto`?

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
>  /// Trait for fallible conversion between types.
Would benefit from more actionable descriptions: when should you implement `TryInto`? When should you not implement `TryInto`, but prefer `Into` ?

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
>  /// Trait for fallible conversion between types.
from rust: 

"""
Simple and safe type conversions that may fail in a controlled way under some circumstances.
"""

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Trait for safe conversion between types.
actually the safe one is TryInto, not Into 🤔

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +    /// Panics if the conversion is not successful.
does it ?

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Trait for computing the negated value of a value of any type.
```suggestion
/// The unary negation operator `-`
```

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +    /// Computes the negation of a given value.
```suggestion
    /// Performs the unary `-` operation.
```
I'm fine with yours, but I think the emphasis should be on the operator itself here

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Trait for computing the logically negated value of a value of any type.
```suggestion
/// The unary logical negation operator `!`.
```

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +    /// Computes the logical negation of a given value.
```suggestion
    /// Performs the unary `!` operation.
```
for focus on the operator

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> -/// The following two traits are for implementing the [] operator. Only one should be implemented
keep as comment?

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Trait for destructing a value of any type.
Needs to document _why_ this trait is required

```suggestion
/// Allows for custom destruction behavior of a type.
///
/// Types implementing this trait will have their `destruct` method called
/// automatically when they go out of scope.
///
/// This trait is particularly important for types that need to perform
/// cleanup operations or side-effects when being destroyed, such as
/// the `Felt252Dict` type that needs to be "squashed" before going out of scope.
```

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +    ///
```suggestion
    /// Destroys the value, performing any necessary cleanup operations.
    ///
    /// This method is called automatically when the value goes out of scope,
    /// allowing for custom destruction behavior.
    ///
```

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Trait for destructing a value of any type in the case of a panic.
```suggestion
/// Allows for destruction of a value in case of a panic.
///
/// This trait is automatically implemented from the `Destruct` implementation for a type.
```

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Trait for creating a default value of any type.
```suggestion
/// A trait for giving a default value to a type.
```

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Trait for creating a default value of any type.
Needs more explanations as this is one of the most used traits. When to implement, how to implement, how to do things the right way? Which types implement default, can I derive it, can I implement it myself ? How do I handle defaults in enums ?

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> -/// Trait helper for implementing `PartialEq` for tuples.
keep as `//` ? (same below?)

2024-11-18 15:28 UTC, enitrat commented on corelib/src/traits.cairo
> +/// Trait that allows to return default values for types used as values in a dictionary.
so if I implement `Felt252DictValue` for my type T can I use it in a dict ?
it's not easy to understand the purpose of this trait, if I'm supposed to be using it, if so, how, etc

2024-11-18 18:52 UTC, TAdev0 commented on corelib/src/traits.cairo
> +/// can safely be destroyed once it's no longer useful. We call this "dropping" a value.
this was copy pasted from Cairo book. Well dropping is a no op destruction right?

2024-11-18 18:53 UTC, TAdev0 commented on corelib/src/traits.cairo
> +/// can safely be destroyed once it's no longer useful. We call this "dropping" a value.
we still have `/// Types that implement the `Drop` trait are automatically destroyed when going out of scope.`

should i reformulate this?

2024-11-18 19:04 UTC, TAdev0 commented on corelib/src/traits.cairo
> +    /// Panics if the conversion is not successful.
yeah you are right. i'm wrong. The unwrapping panics, but the `try_into` itself will just return `Option::None`

2024-11-19 03:33 UTC, enitrat commented on corelib/src/traits.cairo
> +/// can safely be destroyed once it's no longer useful. We call this "dropping" a value.
```suggestion
/// can safely go out of scope once it's no longer useful. We call this "dropping" a value.
```

let's reformulate like this to avoid using "drop" before defining the word

2024-12-02 13:42 UTC, closed without merging