14 - Serde module
cairo-book/cairo-core-lib pull request #15
Opened 2024-11-04 17:48 UTC by TAdev0

2024-11-18 15:42 UTC, enitrat requested changes

2024-11-18 15:42 UTC, enitrat commented on corelib/src/serde.cairo
> +//! Serialization and deserialization of data structures.
```suggestion
//! Serialization and deserialization of types.
```

2024-11-18 15:42 UTC, enitrat commented on corelib/src/serde.cairo
> +//! data structures in a type-safe manner.
```suggestion
//! types in a type-safe manner.
```

2024-11-18 15:42 UTC, enitrat commented on corelib/src/serde.cairo
> +//! the corresponding modules.
Module level doc should help understanding what the process of serializing / deserializing actually looks like. 

Take two examples: Serde an array of 'simple values' (u8, u32 up to u128) or 'complex types' (u256)

Needs some informations:
- Can I derive it?
- Can I implement my own? If so, how?
- What should I respect when writing my own implementation

2024-11-18 15:42 UTC, enitrat commented on corelib/src/serde.cairo
> +//! the corresponding modules.
Something like:
```
//! Serialization and deserialization of data structures.
//!
//! This module provides traits and implementations for converting Cairo data structures into a sequence
//! of felt252 values (serialization) and back (deserialization).
//!
//! When passing values between Cairo and an external environment, serialization and deserialization
//! are necessary to convert Cairo's data types into a format that can be transmitted and vice versa.
//!
//! Cairo's native types like `u256` are serialized into multiple `felt252` values, while custom types
//! are serialized by implementing the `Serde` trait.
```

```
//! A trait that allows for serializing and deserializing values of any type.
//!
//! # Overview
//!
//! The `Serde<T>` trait defines two core operations:
//! - `serialize`: Converts a value into a sequence of `felt252`s
//! - `deserialize`: Reconstructs a value from a sequence of `felt252`s
//!
//! # Examples
//!
//! ## Simple Types (u8, u16, u32, u64, u128)
//! Simple types are serialized into a single felt252:
//! ```
//! let value: u8 = 42;
//! let mut output: Array<felt252> = array![];
//! value.serialize(ref output);
//! assert!(output == array![42]); // Single felt252
//! ```
//!
//! ## Complex Types (u256)
//! Complex types may require multiple felt252s:
//! ```
//! let value: u256 = u256 { low: 1, high: 2 };
//! let mut output: Array<felt252> = array![];
//! value.serialize(ref output);
//! assert!(output == array![1, 2]); // Two felt252s: low and high
//! ```
//!
//! # Implementing Serde
//!
//! ## Using the Derive Macro
//! For structs and enums, you can use the `#[derive(Serde)]` attribute:
//! ```
//! #[derive(Serde)]
//! struct Point { x: u32, y: u32 }
//! ```
//!
//! ## Manual Implementation
//! You can implement `Serde` manually for custom types:
//! ```
//! impl CustomTypeSerde of Serde<CustomType> {
//!     fn serialize(self: @CustomType, ref output: Array<felt252>) {
//!         // Convert your type to felt252(s) and append to output
//!     }
//!
//!     fn deserialize(ref serialized: Span<felt252>) -> Option<CustomType> {
//!         // Reconstruct your type from felt252s
//!     }
//! }
//! ```
/// ```
pub trait Serde<T> {
```

to refine, and add actual, runnable examples

2024-11-18 15:42 UTC, enitrat commented on corelib/src/serde.cairo
> -/// Helper trait for serializing tuple style structs.
keep as // comments maybe?

2024-11-18 15:42 UTC, enitrat commented on corelib/src/serde.cairo
> +/// ```
should this be at the `pub impl` level, not module level?

2024-11-18 18:43 UTC, TAdev0 commented on corelib/src/serde.cairo
> +//! the corresponding modules.
ok, was not sure whether entering into this level of details or not; just applied your suggestion

2024-11-18 18:43 UTC, TAdev0 commented on corelib/src/serde.cairo
> -/// Helper trait for serializing tuple style structs.
done

2024-11-18 18:45 UTC, TAdev0 commented on corelib/src/serde.cairo
> +/// ```
makes more sense indeed, just modified

2024-11-19 03:31 UTC, enitrat commented on corelib/src/serde.cairo
> +//! }
Concrete examples please :)

2024-11-19 03:31 UTC, enitrat commented on corelib/src/serde.cairo
> +    /// the value and appends the result to the output.
```suggestion
    /// Serializes a value into a sequence of `felt252`s.
```

2024-11-19 03:31 UTC, enitrat commented on corelib/src/serde.cairo
> +    /// Returns an option of the deserialized result if the operation is successful, `Option::None`
```suggestion
    /// Deserializes a value from a sequence of `felt252`s.
    /// If the value cannot be deserialized, returns `Option::None`.
```

2024-11-19 03:31 UTC, enitrat commented on corelib/src/serde.cairo
> +    /// `Serde` implementation for types that can be converted into `felt252` using the `Into` trait
```suggestion
    /// A generic `Serde` implementation for types that can be converted into `felt252` using the `Into` trait
```

2024-11-19 03:31 UTC, enitrat commented on corelib/src/serde.cairo
> +    /// impl MyTypeSerde = core::serde::into_felt252_based::SerdeImpl<MyType>;`
```suggestion
```

2024-11-26 11:42 UTC, TAdev0 commented on corelib/src/serde.cairo
> +//! }
just implemented it for Point, not sure my impl for deserialize is the best approach

2024-11-27 07:59 UTC, enitrat commented on corelib/src/serde.cairo
> +//!
🥴🥴🥴

2024-11-27 13:27 UTC, closed without merging